### ISSUE TITLE
"Key Specular not found" error on msh import (Blender 4.0)

### ISSUE THREAD

**Issue by milehighguy-dev** [PrismaticFlower/SWBF-msh-Blender-IO#13]
When I import any model from the assets I get the same error:

```
Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_swbf_msh\__init__.py", line 200, in execute
    extract_scene(filepath, scene)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_swbf_msh\msh_scene_to_blend.py", line 88, in extract_scene
    material_map = extract_materials(folder, scene)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_swbf_msh\msh_scene_to_blend.py", line 75, in extract_materials
    extracted_materials[material_name] = swbf_material_to_blend(material_name, material, folder_path)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_swbf_msh\msh_material_to_blend.py", line 45, in swbf_material_to_blend
    bpy.ops.swbf_msh.generate_material_nodes('EXEC_DEFAULT', material_name=new_mat.name, fail_silently=True) 
  File "D:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_swbf_msh\msh_material_operators.py", line 184, in execute
    bsdf.inputs["Specular"].default_value = 0.0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
Location: D:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:107

```

KeyError: 'bpy_prop_collection[key]: key "Specular" not found'

**Comment by milehighguy-dev** [comment]
on Blender 3.6, the import works
