### ISSUE TITLE
Old games thing?

### ISSUE THREAD

**Issue by Labara** [PrismaticFlower/SWBF-msh-Blender-IO#6]
Trying to open .msh file from an old game and getting this
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_swbf_msh\__init__.py", line 197, in execute
    scene = read_scene(input_file, self.animation_only)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_swbf_msh\msh_scene_read.py", line 51, in read_scene
    with head.read_child() as hedr:
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_swbf_msh\chunked_file_reader.py", line 31, in __enter__
    self.size = self.read_u32()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_swbf_msh\chunked_file_reader.py", line 95, in read_u32
    result = struct.unpack(f"<{num}I", buf)
struct.error: unpack requires a buffer of 4 bytes

**Comment by phantom567459** [comment]
If it is not a SWBF1 or SWBF2 .msh file, this program will not open it.  The lack of a game would make me assume it is a different game that uses the msh extension (but the file formats are not the same).
